/* -*- mode: c; c-basic-offset: 4; indent-tabs-mode: nil -*- */
#define BUILD_BLT_TCL_PROCS 1
#include <bltInt.h>

/* !BEGIN!: Do not edit below this line. */

BltTclIntProcs bltTclIntProcs = {
    TCL_STUB_MAGIC,
    NULL,
    NULL, /* 0 */
    Blt_GetArrayFromObj, /* 1 */
    Blt_NewArrayObj, /* 2 */
    Blt_IsArrayObj, /* 3 */
    Blt_Assert, /* 4 */
    Blt_DBuffer_VarAppend, /* 5 */
    Blt_DBuffer_Format, /* 6 */
    Blt_DBuffer_Init, /* 7 */
    Blt_DBuffer_Free, /* 8 */
    Blt_DBuffer_Extend, /* 9 */
    Blt_DBuffer_AppendData, /* 10 */
    Blt_DBuffer_AppendString, /* 11 */
    Blt_DBuffer_DeleteData, /* 12 */
    Blt_DBuffer_InsertData, /* 13 */
    Blt_DBuffer_SetFromObj, /* 14 */
    Blt_DBuffer_Concat, /* 15 */
    Blt_DBuffer_Resize, /* 16 */
    Blt_DBuffer_SetLength, /* 17 */
    Blt_DBuffer_Create, /* 18 */
    Blt_DBuffer_Destroy, /* 19 */
    Blt_DBuffer_LoadFile, /* 20 */
    Blt_DBuffer_SaveFile, /* 21 */
    Blt_DBuffer_AppendByte, /* 22 */
    Blt_DBuffer_AppendShort, /* 23 */
    Blt_DBuffer_AppendInt, /* 24 */
    Blt_DBuffer_ByteArrayObj, /* 25 */
    Blt_DBuffer_StringObj, /* 26 */
    Blt_DBuffer_String, /* 27 */
    Blt_DBuffer_Base64Decode, /* 28 */
    Blt_DBuffer_Base64EncodeToObj, /* 29 */
    Blt_DBuffer_AppendBase85, /* 30 */
    Blt_DBuffer_AppendBase64, /* 31 */
    Blt_SimplifyLine, /* 32 */
    Blt_LineRectClip, /* 33 */
    Blt_PointInPolygon, /* 34 */
    Blt_PolygonInRegion, /* 35 */
    Blt_PointInSegments, /* 36 */
    Blt_PolyRectClip, /* 37 */
    Blt_GetProjection, /* 38 */
    Blt_GetProjection2, /* 39 */
    Blt_ConvexHull, /* 40 */
    Blt_InitCmd, /* 41 */
    Blt_InitCmds, /* 42 */
    Blt_FreeMesh, /* 43 */
    Blt_GetMeshFromObj, /* 44 */
    Blt_GetMesh, /* 45 */
    Blt_Triangulate, /* 46 */
    Blt_Mesh_CreateNotifier, /* 47 */
    Blt_Mesh_DeleteNotifier, /* 48 */
    Blt_Mesh_Name, /* 49 */
    Blt_Mesh_Type, /* 50 */
    Blt_Mesh_GetVertices, /* 51 */
    Blt_Mesh_GetHull, /* 52 */
    Blt_Mesh_GetExtents, /* 53 */
    Blt_Mesh_GetTriangles, /* 54 */
    Blt_GetVariableNamespace, /* 55 */
    Blt_GetCommandNamespace, /* 56 */
    Blt_EnterNamespace, /* 57 */
    Blt_LeaveNamespace, /* 58 */
    Blt_ParseObjectName, /* 59 */
    Blt_MakeQualifiedName, /* 60 */
    Blt_MakeQualifiedNameObj, /* 61 */
    Blt_CommandExists, /* 62 */
    Blt_GetOpFromObj, /* 63 */
    Blt_CreateSpline, /* 64 */
    Blt_EvaluateSpline, /* 65 */
    Blt_FreeSpline, /* 66 */
    Blt_CreateParametricCubicSpline, /* 67 */
    Blt_EvaluateParametricCubicSpline, /* 68 */
    Blt_FreeParametricCubicSpline, /* 69 */
    Blt_CreateCatromSpline, /* 70 */
    Blt_EvaluateCatromSpline, /* 71 */
    Blt_FreeCatromSpline, /* 72 */
    Blt_ComputeNaturalSpline, /* 73 */
    Blt_ComputeQuadraticSpline, /* 74 */
    Blt_ComputeNaturalParametricSpline, /* 75 */
    Blt_ComputeCatromParametricSpline, /* 76 */
    Blt_Tags_Create, /* 77 */
    Blt_Tags_Destroy, /* 78 */
    Blt_Tags_Init, /* 79 */
    Blt_Tags_Reset, /* 80 */
    Blt_Tags_ItemHasTag, /* 81 */
    Blt_Tags_AddTag, /* 82 */
    Blt_Tags_AddItemToTag, /* 83 */
    Blt_Tags_ForgetTag, /* 84 */
    Blt_Tags_RemoveItemFromTag, /* 85 */
    Blt_Tags_ClearTagsFromItem, /* 86 */
    Blt_Tags_AppendTagsToChain, /* 87 */
    Blt_Tags_AppendTagsToObj, /* 88 */
    Blt_Tags_AppendAllTagsToObj, /* 89 */
    Blt_Tags_GetItemList, /* 90 */
    Blt_Tags_GetTable, /* 91 */
    Blt_DictionaryCompare, /* 92 */
    Blt_GetUid, /* 93 */
    Blt_FreeUid, /* 94 */
    Blt_FindUid, /* 95 */
    Blt_CreatePipeline, /* 96 */
    Blt_DetachPids, /* 97 */
    Blt_InitHexTable, /* 98 */
    Blt_DStringAppendElements, /* 99 */
    Blt_LoadLibrary, /* 100 */
    Blt_Panic, /* 101 */
    Blt_Warn, /* 102 */
    Blt_OpenFile, /* 103 */
    Blt_Itoa, /* 104 */
    Blt_Ltoa, /* 105 */
    Blt_Utoa, /* 106 */
    Blt_Dtoa, /* 107 */
    Blt_DecodeHexadecimal, /* 108 */
    Blt_DecodeBase64, /* 109 */
    Blt_DecodeBase85, /* 110 */
    Blt_DecodeAscii85, /* 111 */
    Blt_DecodeBase64ToBuffer, /* 112 */
    Blt_DecodeHexadecimalToObj, /* 113 */
    Blt_DecodeBase64ToObj, /* 114 */
    Blt_DecodeBase85ToObj, /* 115 */
    Blt_EncodeHexadecimal, /* 116 */
    Blt_EncodeBase64, /* 117 */
    Blt_EncodeBase85, /* 118 */
    Blt_EncodeAscii85, /* 119 */
    Blt_EncodeHexadecimalToObj, /* 120 */
    Blt_EncodeBase64ToObj, /* 121 */
    Blt_EncodeBase85ToObj, /* 122 */
    Blt_HexadecimalDecodeBufferSize, /* 123 */
    Blt_HexadecimalEncodeBufferSize, /* 124 */
    Blt_Base64DecodeBufferSize, /* 125 */
    Blt_Base64EncodeBufferSize, /* 126 */
    Blt_Base85DecodeBufferSize, /* 127 */
    Blt_Base85EncodeBufferSize, /* 128 */
    Blt_Ascii85DecodeBufferSize, /* 129 */
    Blt_Ascii85EncodeBufferSize, /* 130 */
    Blt_IsBase64, /* 131 */
    Blt_GetTimeFromObj, /* 132 */
    Blt_GetTime, /* 133 */
    Blt_SecondsToDate, /* 134 */
    Blt_DateToSeconds, /* 135 */
    Blt_FormatDate, /* 136 */
    Blt_GetPositionFromObj, /* 137 */
    Blt_ObjIsInteger, /* 138 */
    Blt_GetLong, /* 139 */
    Blt_GetLongFromObj, /* 140 */
    Blt_SetLongObj, /* 141 */
    Blt_NewLongObj, /* 142 */
    Blt_IsLongObj, /* 143 */
    Blt_GetUnsignedLong, /* 144 */
    Blt_GetUnsignedLongFromObj, /* 145 */
    Blt_SetUnsignedLongObj, /* 146 */
    Blt_NewUnsignedLongObj, /* 147 */
    Blt_IsUnsignedLongObj, /* 148 */
    Blt_GetInt64, /* 149 */
    Blt_GetInt64FromObj, /* 150 */
    Blt_SetInt64Obj, /* 151 */
    Blt_NewInt64Obj, /* 152 */
    Blt_IsInt64Obj, /* 153 */
    Blt_GetDouble, /* 154 */
    Blt_GetDoubleFromObj, /* 155 */
    Blt_SetDoubleObj, /* 156 */
    Blt_NewDoubleObj, /* 157 */
    Blt_IsDoubleObj, /* 158 */
    Blt_FmtString, /* 159 */
    Blt_LowerCase, /* 160 */
    Blt_UpperCase, /* 161 */
    Blt_GetPlatformId, /* 162 */
    Blt_LastError, /* 163 */
    Blt_NaN, /* 164 */
    Blt_AlmostEquals, /* 165 */
    Blt_ConvertListToList, /* 166 */
    Blt_RegisterObjTypes, /* 167 */
    Blt_GetCachedVar, /* 168 */
    Blt_FreeCachedVars, /* 169 */
};

/* !END!: Do not edit above this line. */
