/* -*- mode: c; c-basic-offset: 4; indent-tabs-mode: nil -*- */
#define BUILD_BLT_TCL_PROCS 1
#include <bltInt.h>

extern BltTclIntProcs bltTclIntProcs;

/* !BEGIN!: Do not edit below this line. */

static BltTclStubHooks bltTclStubHooks = {
    &bltTclIntProcs
};

BltTclProcs bltTclProcs = {
    TCL_STUB_MAGIC,
    &bltTclStubHooks,
    NULL, /* 0 */
    Blt_AllocInit, /* 1 */
    Blt_Malloc, /* 2 */
    Blt_Free, /* 3 */
    Blt_Realloc, /* 4 */
    Blt_Calloc, /* 5 */
    Blt_MallocAbortOnError, /* 6 */
    Blt_CallocAbortOnError, /* 7 */
    Blt_ReallocAbortOnError, /* 8 */
    Blt_Strndup, /* 9 */
    Blt_Strdup, /* 10 */
    Blt_StrdupAbortOnError, /* 11 */
    Blt_StrndupAbortOnError, /* 12 */
    Blt_Chain_Init, /* 13 */
    Blt_Chain_Create, /* 14 */
    Blt_Chain_Destroy, /* 15 */
    Blt_Chain_NewLink, /* 16 */
    Blt_Chain_AllocLink, /* 17 */
    Blt_Chain_Append, /* 18 */
    Blt_Chain_Prepend, /* 19 */
    Blt_Chain_Reset, /* 20 */
    Blt_Chain_InitLink, /* 21 */
    Blt_Chain_LinkAfter, /* 22 */
    Blt_Chain_LinkBefore, /* 23 */
    Blt_Chain_UnlinkLink, /* 24 */
    Blt_Chain_DeleteLink, /* 25 */
    Blt_Chain_GetNthLink, /* 26 */
    Blt_Chain_Sort, /* 27 */
    Blt_Chain_Reverse, /* 28 */
    Blt_Chain_IsBefore, /* 29 */
    Blt_InitHashTable, /* 30 */
    Blt_InitHashTableWithPool, /* 31 */
    Blt_DeleteHashTable, /* 32 */
    Blt_DeleteHashEntry, /* 33 */
    Blt_FirstHashEntry, /* 34 */
    Blt_NextHashEntry, /* 35 */
    Blt_HashStats, /* 36 */
    Blt_Tags_Create, /* 37 */
    Blt_Tags_Destroy, /* 38 */
    Blt_Tags_Init, /* 39 */
    Blt_Tags_Reset, /* 40 */
    Blt_Tags_ItemHasTag, /* 41 */
    Blt_Tags_AddTag, /* 42 */
    Blt_Tags_AddItemToTag, /* 43 */
    Blt_Tags_ForgetTag, /* 44 */
    Blt_Tags_RemoveItemFromTag, /* 45 */
    Blt_Tags_ClearTagsFromItem, /* 46 */
    Blt_Tags_AppendTagsToChain, /* 47 */
    Blt_Tags_AppendTagsToObj, /* 48 */
    Blt_Tags_AppendAllTagsToObj, /* 49 */
    Blt_Tags_GetItemList, /* 50 */
    Blt_Tags_GetTable, /* 51 */
    Blt_List_Init, /* 52 */
    Blt_List_Reset, /* 53 */
    Blt_List_Create, /* 54 */
    Blt_List_Destroy, /* 55 */
    Blt_List_CreateNode, /* 56 */
    Blt_List_DeleteNode, /* 57 */
    Blt_List_Append, /* 58 */
    Blt_List_Prepend, /* 59 */
    Blt_List_LinkAfter, /* 60 */
    Blt_List_LinkBefore, /* 61 */
    Blt_List_UnlinkNode, /* 62 */
    Blt_List_GetNode, /* 63 */
    Blt_List_DeleteNodeByKey, /* 64 */
    Blt_List_GetNthNode, /* 65 */
    Blt_List_Sort, /* 66 */
    Blt_Pool_Create, /* 67 */
    Blt_Pool_Destroy, /* 68 */
    Blt_Tree_GetUid, /* 69 */
    Blt_Tree_GetUidFromNode, /* 70 */
    Blt_Tree_GetNextId, /* 71 */
    Blt_Tree_CreateNode, /* 72 */
    Blt_Tree_CreateNodeWithId, /* 73 */
    Blt_Tree_DeleteNode, /* 74 */
    Blt_Tree_MoveNode, /* 75 */
    Blt_Tree_GetNodeFromIndex, /* 76 */
    Blt_Tree_FindChild, /* 77 */
    Blt_Tree_NextNode, /* 78 */
    Blt_Tree_PrevNode, /* 79 */
    Blt_Tree_FirstChild, /* 80 */
    Blt_Tree_LastChild, /* 81 */
    Blt_Tree_IsBefore, /* 82 */
    Blt_Tree_IsAncestor, /* 83 */
    Blt_Tree_PrivateValue, /* 84 */
    Blt_Tree_PublicValue, /* 85 */
    Blt_Tree_GetValue, /* 86 */
    Blt_Tree_ValueExists, /* 87 */
    Blt_Tree_SetValue, /* 88 */
    Blt_Tree_UnsetValue, /* 89 */
    Blt_Tree_AppendObjValue, /* 90 */
    Blt_Tree_ListAppendObjValue, /* 91 */
    Blt_Tree_ListReplaceObjValues, /* 92 */
    Blt_Tree_GetArrayObjValue, /* 93 */
    Blt_Tree_SetArrayValue, /* 94 */
    Blt_Tree_UnsetArrayValue, /* 95 */
    Blt_Tree_AppendArrayObjValue, /* 96 */
    Blt_Tree_ListAppendArrayObjValue, /* 97 */
    Blt_Tree_ListReplaceArrayObjValues, /* 98 */
    Blt_Tree_ArrayValueExists, /* 99 */
    Blt_Tree_ArrayNames, /* 100 */
    Blt_Tree_GetScalarValueByUid, /* 101 */
    Blt_Tree_SetScalarValueByUid, /* 102 */
    Blt_Tree_UnsetScalarValueByUid, /* 103 */
    Blt_Tree_AppendScalarObjValueByUid, /* 104 */
    Blt_Tree_ListAppendScalarObjValueByUid, /* 105 */
    Blt_Tree_ListReplaceScalarObjValuesByUid, /* 106 */
    Blt_Tree_ScalarValueExistsByUid, /* 107 */
    Blt_Tree_FirstValue, /* 108 */
    Blt_Tree_NextValue, /* 109 */
    Blt_Tree_Apply, /* 110 */
    Blt_Tree_ApplyDFS, /* 111 */
    Blt_Tree_ApplyBFS, /* 112 */
    Blt_Tree_SortNode, /* 113 */
    Blt_Tree_Exists, /* 114 */
    Blt_Tree_Open, /* 115 */
    Blt_Tree_Close, /* 116 */
    Blt_Tree_Attach, /* 117 */
    Blt_Tree_GetFromObj, /* 118 */
    Blt_Tree_Size, /* 119 */
    Blt_Tree_CreateTrace, /* 120 */
    Blt_Tree_DeleteTrace, /* 121 */
    Blt_Tree_CreateEventHandler, /* 122 */
    Blt_Tree_DeleteEventHandler, /* 123 */
    Blt_Tree_RelabelNode, /* 124 */
    Blt_Tree_RelabelNodeWithoutNotify, /* 125 */
    Blt_Tree_NodeIdAscii, /* 126 */
    Blt_Tree_NodePathObj, /* 127 */
    Blt_Tree_NodePath, /* 128 */
    Blt_Tree_NodeRelativePath, /* 129 */
    Blt_Tree_NodePosition, /* 130 */
    Blt_Tree_ClearTags, /* 131 */
    Blt_Tree_HasTag, /* 132 */
    Blt_Tree_AddTag, /* 133 */
    Blt_Tree_RemoveTag, /* 134 */
    Blt_Tree_ForgetTag, /* 135 */
    Blt_Tree_TagHashTable, /* 136 */
    Blt_Tree_TagTableIsShared, /* 137 */
    Blt_Tree_NewTagTable, /* 138 */
    Blt_Tree_FirstTag, /* 139 */
    Blt_Tree_Depth, /* 140 */
    Blt_Tree_RegisterFormat, /* 141 */
    Blt_Tree_RememberTag, /* 142 */
    Blt_Tree_GetNodeFromObj, /* 143 */
    Blt_Tree_GetNodeIterator, /* 144 */
    Blt_Tree_FirstTaggedNode, /* 145 */
    Blt_Tree_NextTaggedNode, /* 146 */
    Blt_Tree_GetPathSeparator, /* 147 */
    Blt_Tree_SetPathSeparator, /* 148 */
    blt_table_release_tags, /* 149 */
    blt_table_new_tags, /* 150 */
    blt_table_get_column_tag_table, /* 151 */
    blt_table_get_row_tag_table, /* 152 */
    blt_table_exists, /* 153 */
    blt_table_create, /* 154 */
    blt_table_open, /* 155 */
    blt_table_close, /* 156 */
    blt_table_clear, /* 157 */
    blt_table_pack, /* 158 */
    blt_table_reset, /* 159 */
    blt_table_same_object, /* 160 */
    blt_table_row_get_label_table, /* 161 */
    blt_table_column_get_label_table, /* 162 */
    blt_table_get_row, /* 163 */
    blt_table_get_column, /* 164 */
    blt_table_get_row_by_label, /* 165 */
    blt_table_get_column_by_label, /* 166 */
    blt_table_get_row_by_index, /* 167 */
    blt_table_get_column_by_index, /* 168 */
    blt_table_set_row_label, /* 169 */
    blt_table_set_column_label, /* 170 */
    blt_table_name_to_column_type, /* 171 */
    blt_table_set_column_type, /* 172 */
    blt_table_column_type_to_name, /* 173 */
    blt_table_set_column_tag, /* 174 */
    blt_table_set_row_tag, /* 175 */
    blt_table_create_row, /* 176 */
    blt_table_create_column, /* 177 */
    blt_table_extend_rows, /* 178 */
    blt_table_extend_columns, /* 179 */
    blt_table_delete_row, /* 180 */
    blt_table_delete_column, /* 181 */
    blt_table_move_rows, /* 182 */
    blt_table_move_columns, /* 183 */
    blt_table_get_obj, /* 184 */
    blt_table_set_obj, /* 185 */
    blt_table_get_string, /* 186 */
    blt_table_set_string_rep, /* 187 */
    blt_table_set_string, /* 188 */
    blt_table_append_string, /* 189 */
    blt_table_set_bytes, /* 190 */
    blt_table_get_double, /* 191 */
    blt_table_set_double, /* 192 */
    blt_table_get_long, /* 193 */
    blt_table_set_long, /* 194 */
    blt_table_get_boolean, /* 195 */
    blt_table_set_boolean, /* 196 */
    blt_table_set_int64, /* 197 */
    blt_table_get_int64, /* 198 */
    blt_table_get_value, /* 199 */
    blt_table_set_value, /* 200 */
    blt_table_unset_value, /* 201 */
    blt_table_value_exists, /* 202 */
    blt_table_value_string, /* 203 */
    blt_table_value_bytes, /* 204 */
    blt_table_value_length, /* 205 */
    blt_table_tags_are_shared, /* 206 */
    blt_table_clear_row_tags, /* 207 */
    blt_table_clear_column_tags, /* 208 */
    blt_table_get_row_tags, /* 209 */
    blt_table_get_column_tags, /* 210 */
    blt_table_get_tagged_rows, /* 211 */
    blt_table_get_tagged_columns, /* 212 */
    blt_table_row_has_tag, /* 213 */
    blt_table_column_has_tag, /* 214 */
    blt_table_forget_row_tag, /* 215 */
    blt_table_forget_column_tag, /* 216 */
    blt_table_unset_row_tag, /* 217 */
    blt_table_unset_column_tag, /* 218 */
    blt_table_first_column, /* 219 */
    blt_table_last_column, /* 220 */
    blt_table_next_column, /* 221 */
    blt_table_previous_column, /* 222 */
    blt_table_first_row, /* 223 */
    blt_table_last_row, /* 224 */
    blt_table_next_row, /* 225 */
    blt_table_previous_row, /* 226 */
    blt_table_row_spec, /* 227 */
    blt_table_column_spec, /* 228 */
    blt_table_iterate_rows, /* 229 */
    blt_table_iterate_columns, /* 230 */
    blt_table_iterate_rows_objv, /* 231 */
    blt_table_iterate_columns_objv, /* 232 */
    blt_table_free_iterator_objv, /* 233 */
    blt_table_iterate_all_rows, /* 234 */
    blt_table_iterate_all_columns, /* 235 */
    blt_table_first_tagged_row, /* 236 */
    blt_table_first_tagged_column, /* 237 */
    blt_table_next_tagged_row, /* 238 */
    blt_table_next_tagged_column, /* 239 */
    blt_table_list_rows, /* 240 */
    blt_table_list_columns, /* 241 */
    blt_table_clear_row_traces, /* 242 */
    blt_table_clear_column_traces, /* 243 */
    blt_table_create_trace, /* 244 */
    blt_table_trace_column, /* 245 */
    blt_table_trace_row, /* 246 */
    blt_table_create_column_trace, /* 247 */
    blt_table_create_column_tag_trace, /* 248 */
    blt_table_create_row_trace, /* 249 */
    blt_table_create_row_tag_trace, /* 250 */
    blt_table_delete_trace, /* 251 */
    blt_table_create_notifier, /* 252 */
    blt_table_create_row_notifier, /* 253 */
    blt_table_create_row_tag_notifier, /* 254 */
    blt_table_create_column_notifier, /* 255 */
    blt_table_create_column_tag_notifier, /* 256 */
    blt_table_delete_notifier, /* 257 */
    blt_table_sort_init, /* 258 */
    blt_table_sort_rows, /* 259 */
    blt_table_sort_row_map, /* 260 */
    blt_table_sort_finish, /* 261 */
    blt_table_get_compare_proc, /* 262 */
    blt_table_get_row_map, /* 263 */
    blt_table_get_column_map, /* 264 */
    blt_table_set_row_map, /* 265 */
    blt_table_set_column_map, /* 266 */
    blt_table_restore, /* 267 */
    blt_table_file_restore, /* 268 */
    blt_table_register_format, /* 269 */
    blt_table_unset_keys, /* 270 */
    blt_table_get_keys, /* 271 */
    blt_table_set_keys, /* 272 */
    blt_table_key_lookup, /* 273 */
    blt_table_get_column_limits, /* 274 */
    blt_table_row, /* 275 */
    blt_table_column, /* 276 */
    blt_table_row_index, /* 277 */
    blt_table_column_index, /* 278 */
    Blt_VecMin, /* 279 */
    Blt_VecMax, /* 280 */
    Blt_AllocVectorId, /* 281 */
    Blt_SetVectorChangedProc, /* 282 */
    Blt_FreeVectorId, /* 283 */
    Blt_GetVectorById, /* 284 */
    Blt_NameOfVectorId, /* 285 */
    Blt_NameOfVector, /* 286 */
    Blt_VectorNotifyPending, /* 287 */
    Blt_CreateVector, /* 288 */
    Blt_CreateVector2, /* 289 */
    Blt_GetVector, /* 290 */
    Blt_GetVectorFromObj, /* 291 */
    Blt_VectorExists, /* 292 */
    Blt_ResetVector, /* 293 */
    Blt_ResizeVector, /* 294 */
    Blt_DeleteVectorByName, /* 295 */
    Blt_DeleteVector, /* 296 */
    Blt_ExprVector, /* 297 */
    Blt_InstallIndexProc, /* 298 */
    Blt_VectorExists2, /* 299 */
};

/* !END!: Do not edit above this line. */
